# Generated by Django 4.0.8 on 2023-01-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(default='admin', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
